simpletest:
    script:
        - pwd
        - conda --version
        - conda env update -q --name gerdaenv --file gerdaenv.yml
        - conda activate gerdaenv
        - which python3
        - python3 -m testing.testrunner
